name: license_check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - "stt_recorder/pubspec.yaml"
      - "stt_recorder_platform_interface/pubspec.yaml"
      - "stt_recorder_android/pubspec.yaml"
      - "stt_recorder_ios/pubspec.yaml"
      - "stt_recorder_macos/pubspec.yaml"
      - "stt_recorder_web/pubspec.yaml"
      - ".github/workflows/license_check.yaml"
  push:
    branches:
      - main
    paths:
      - "stt_recorder/pubspec.yaml"
      - "stt_recorder_platform_interface/pubspec.yaml"
      - "stt_recorder_android/pubspec.yaml"
      - "stt_recorder_ios/pubspec.yaml"
      - "stt_recorder_macos/pubspec.yaml"
      - "stt_recorder_web/pubspec.yaml"
      - ".github/workflows/license_check.yaml"

jobs:
  license_check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        working_directory:
          - stt_recorder
          - stt_recorder_platform_interface
          - stt_recorder_android
          - stt_recorder_ios
          - stt_recorder_macos
          - stt_recorder_web
    defaults:
      run:
        working-directory: ${{ matrix.working_directory }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v6

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.41.1
          cache: true
          cache-key: flutter-:os:-stable-3.41.1-:arch:-:hash:-${{ hashFiles('**/pubspec.lock') }}

      - name: 📦 Install Dependencies
        run: flutter pub get

      - name: 👨‍⚖️ Check licenses
        run: |
          dart pub global activate very_good_cli
          dart pub global run very_good_cli:very_good packages check licenses \
            --allowed=MIT,BSD-3-Clause,BSD-2-Clause,Apache-2.0,Zlib \
            --dependency-type=direct-main,transitive
