name: publish_stt_recorder_platform_interface

on:
  push:
    tags:
      - "stt_recorder_platform_interface-v*"

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/publish_pub_dev.yaml
    with:
      package: stt_recorder_platform_interface
